// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCex56xbcyoEsItkRAmlq6_Pegm7GfEvEk',
    appId: '1:57168277201:web:6440f5de520c1754261ff0',
    messagingSenderId: '57168277201',
    projectId: 'fir-authv1-38a03',
    authDomain: 'fir-authv1-38a03.firebaseapp.com',
    storageBucket: 'fir-authv1-38a03.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM4YaCHcxiVGQHp6EPkAxy7BBuFVbk5bg',
    appId: '1:57168277201:android:609edcfcb5ca077b261ff0',
    messagingSenderId: '57168277201',
    projectId: 'fir-authv1-38a03',
    storageBucket: 'fir-authv1-38a03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo2pG4bj4k_gLC9G4bcDcohsXHlYQcQ6E',
    appId: '1:57168277201:ios:bf95a244f9f8626a261ff0',
    messagingSenderId: '57168277201',
    projectId: 'fir-authv1-38a03',
    storageBucket: 'fir-authv1-38a03.appspot.com',
    iosBundleId: 'com.example.firebaseAuthv1Isidro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo2pG4bj4k_gLC9G4bcDcohsXHlYQcQ6E',
    appId: '1:57168277201:ios:bf95a244f9f8626a261ff0',
    messagingSenderId: '57168277201',
    projectId: 'fir-authv1-38a03',
    storageBucket: 'fir-authv1-38a03.appspot.com',
    iosBundleId: 'com.example.firebaseAuthv1Isidro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCex56xbcyoEsItkRAmlq6_Pegm7GfEvEk',
    appId: '1:57168277201:web:5018e9a4d910256f261ff0',
    messagingSenderId: '57168277201',
    projectId: 'fir-authv1-38a03',
    authDomain: 'fir-authv1-38a03.firebaseapp.com',
    storageBucket: 'fir-authv1-38a03.appspot.com',
  );
}
